### ISSUE TITLE
Error in Upload tests after updating netty 4.1.49 -> 4.1.50 (HttpPostMultipartRequestDecoder regression)

### ISSUE THREAD

**Issue by doom369** [netty/netty#10281]
Haven't dig into it yet, however I saw there were 3 different PRs changes in `HttpPostMultipartRequestDecoder`.

```
java.lang.IndexOutOfBoundsException: writerIndex(215369) + minWritableBytes(215369) exceeds maxCapacity(215369): UnpooledSlicedByteBuf(ridx: 215369, widx: 215369, cap: 215369/215369, unwrapped: CompositeByteBuf(ridx: 0, widx: 215369, cap: 215369, components=57))
	at io.netty.buffer.AbstractByteBuf.ensureWritable0(AbstractByteBuf.java:295) ~[netty-buffer-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.buffer.AbstractByteBuf.ensureWritable(AbstractByteBuf.java:282) ~[netty-buffer-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1104) ~[netty-buffer-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1097) ~[netty-buffer-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1088) ~[netty-buffer-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.buffer.WrappedByteBuf.writeBytes(WrappedByteBuf.java:780) ~[netty-buffer-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.buffer.AdvancedLeakAwareByteBuf.writeBytes(AdvancedLeakAwareByteBuf.java:593) ~[netty-buffer-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.handler.codec.http.multipart.HttpPostMultipartRequestDecoder.offer(HttpPostMultipartRequestDecoder.java:340) ~[netty-codec-http-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.handler.codec.http.multipart.HttpPostMultipartRequestDecoder.offer(HttpPostMultipartRequestDecoder.java:52) ~[netty-codec-http-4.1.50.Final.jar:4.1.50.Final]
	at io.netty.handler.codec.http.multipart.HttpPostRequestDecoder.offer(HttpPostRequestDecoder.java:223) ~[netty-codec-http-4.1.50.Final.jar:4.1.50.Final]
```

Look like related to this code in `HttpPostMultipartRequestDecoder`:

```
        ByteBuf buf = content.content();
        if (undecodedChunk == null) {
            undecodedChunk = isLastChunk ?
                    // Take a slice instead of copying when the first chunk is also the last
                    // as undecodedChunk.writeBytes will never be called.
                    buf.retainedSlice() :
                    // Maybe we should better not copy here for performance reasons but this will need
                    // more care by the caller to release the content in a correct manner later
                    // So maybe something to optimize on a later stage
                    //
                    // We are explicit allocate a buffer and NOT calling copy() as otherwise it may set a maxCapacity
                    // which is not really usable for us as we may exceed it once we add more bytes.
                    buf.alloc().buffer(buf.readableBytes()).writeBytes(buf);
        } else {
            undecodedChunk.writeBytes(buf);
        }
```

comment for `buf.retainedSlice()` is not true, when first chunk is last chunk in case of `AggregatedFullHttpRequest`.

Could be reproduced with regular Upload example and added additional handler: 
`pipeline.addLast(new HttpObjectAggregator(300000));`

**Comment by fabienrenaud** [comment]
@doom369 Can you provide your full channel pipeline?

**Comment by doom369** [comment]
@fabienrenaud sure, you can reproduce it with `HttpUploadServerHandler`:

```
public class HttpUploadServerInitializer extends ChannelInitializer<SocketChannel> {

    private final SslContext sslCtx;

    public HttpUploadServerInitializer(SslContext sslCtx) {
        this.sslCtx = sslCtx;
    }

    @Override
    public void initChannel(SocketChannel ch) {
        ChannelPipeline pipeline = ch.pipeline();

        if (sslCtx != null) {
            pipeline.addLast(sslCtx.newHandler(ch.alloc()));
        }

        pipeline.addLast(new HttpRequestDecoder());
        pipeline.addLast(new HttpResponseEncoder());
        pipeline.addLast(new HttpObjectAggregator(300000));

        // Remove the following line if you don't want automatic content compression.
        pipeline.addLast(new HttpContentCompressor());

        pipeline.addLast(new HttpUploadServerHandler());
    }
}
```

**Comment by amizurov** [comment]
Hi, I think the main problem here that we received `AggregatedFullHttpMessage` but our example `HttpUploadServerHandler` doesn't handle it correctly and invokes `offer(..)` twice firstly in constructor and then when handle chunks. Sow what if we add a guardian to `HttpPostMultipartRequestDecoder` for avoid incorrect behavior :
```
 @Override
    public HttpPostMultipartRequestDecoder offer(HttpContent content) {
        checkDestroyed();
        checkLastChunkReceived();
        ...
```
and also try to fix our example to support `HttpObjectAggregator`. WDYT @doom369 , @normanmaurer @fabienrenaud  ?

**Comment by doom369** [comment]
@amizurov could you please make PR, I'm not sure I got the idea.

**Comment by amizurov** [comment]
> @amizurov could you please make PR, I'm not sure I got the idea.

Yes, I'll try to do it next week

**Comment by 88250** [comment]
I also encountered this problem and look forward to fixing it, thank you.

**Comment by doom369** [comment]
@88250 I fixed it in own code by extending the **HttpPostMultipartRequestDecoder** and overriding the behavior, however it would be better to fix within the initial decoder of course.

**Comment by IgorAlelekov** [comment]
@doom369 , looks like that the same fix should be done in HttpPostStandardRequestDecoder as well

**Comment by doom369** [comment]
@IgorAlelekov yes,

```
/**
 * copy of HttpPostRequestDecoder to fix
 * https://github.com/netty/netty/issues/10281
 */
public class BlynkHttpPostRequestDecoder implements InterfaceHttpPostRequestDecoder {

    private final InterfaceHttpPostRequestDecoder decoder;

    /**
     *
     * @param request
     *            the request to decode
     * @throws NullPointerException
     *             for request
     * @throws HttpPostRequestDecoder.ErrorDataDecoderException
     *             if the default charset was wrong when decoding or other
     *             errors
     */
    public BlynkHttpPostRequestDecoder(HttpRequest request) {
        this(new DefaultHttpDataFactory(DefaultHttpDataFactory.MINSIZE), request, HttpConstants.DEFAULT_CHARSET);
    }

    /**
     *
     * @param factory
     *            the factory used to create InterfaceHttpData
     * @param request
     *            the request to decode
     * @throws NullPointerException
     *             for request or factory
     * @throws HttpPostRequestDecoder.ErrorDataDecoderException
     *             if the default charset was wrong when decoding or other
     *             errors
     */
    public BlynkHttpPostRequestDecoder(HttpDataFactory factory, HttpRequest request) {
        this(factory, request, HttpConstants.DEFAULT_CHARSET);
    }

    /**
     *
     * @param factory
     *            the factory used to create InterfaceHttpData
     * @param request
     *            the request to decode
     * @param charset
     *            the charset to use as default
     * @throws NullPointerException
     *             for request or charset or factory
     * @throws HttpPostRequestDecoder.ErrorDataDecoderException
     *             if the default charset was wrong when decoding or other
     *             errors
     */
    public BlynkHttpPostRequestDecoder(HttpDataFactory factory, HttpRequest request, Charset charset) {
        ObjectUtil.checkNotNull(factory, "factory");
        ObjectUtil.checkNotNull(request, "request");
        ObjectUtil.checkNotNull(charset, "charset");

        // Fill default values
        if (isMultipart(request)) {
            decoder = new BlynkHttpPostMultipartRequestDecoder(factory, request, charset);
        } else {
            decoder = new HttpPostStandardRequestDecoder(factory, request, charset);
        }
    }

    /**
     * Check if the given request is a multipart request
     * @return True if the request is a Multipart request
     */
    public static boolean isMultipart(HttpRequest request) {
        String mimeType = request.headers().get(HttpHeaderNames.CONTENT_TYPE);
        if (mimeType != null && mimeType.startsWith(HttpHeaderValues.MULTIPART_FORM_DATA.toString())) {
            return getMultipartDataBoundary(mimeType) != null;
        }
        return false;
    }

    /**
     * Check from the request ContentType if this request is a Multipart request.
     * @return an array of String if multipartDataBoundary exists with the multipartDataBoundary
     * as first element, charset if any as second (missing if not set), else null
     */
    protected static String[] getMultipartDataBoundary(String contentType) {
        // Check if Post using "multipart/form-data; boundary=--89421926422648 [; charset=xxx]"
        String[] headerContentType = splitHeaderContentType(contentType);
        final String multiPartHeader = HttpHeaderValues.MULTIPART_FORM_DATA.toString();
        if (headerContentType[0].regionMatches(true, 0, multiPartHeader, 0, multiPartHeader.length())) {
            int mrank;
            int crank;
            final String boundaryHeader = HttpHeaderValues.BOUNDARY.toString();
            if (headerContentType[1].regionMatches(true, 0, boundaryHeader, 0, boundaryHeader.length())) {
                mrank = 1;
                crank = 2;
            } else if (headerContentType[2].regionMatches(true, 0, boundaryHeader, 0, boundaryHeader.length())) {
                mrank = 2;
                crank = 1;
            } else {
                return null;
            }
            String boundary = StringUtil.substringAfter(headerContentType[mrank], '=');
            if (boundary == null) {
                throw new HttpPostRequestDecoder.ErrorDataDecoderException("Needs a boundary value");
            }
            if (boundary.charAt(0) == '"') {
                String bound = boundary.trim();
                int index = bound.length() - 1;
                if (bound.charAt(index) == '"') {
                    boundary = bound.substring(1, index);
                }
            }
            final String charsetHeader = HttpHeaderValues.CHARSET.toString();
            if (headerContentType[crank].regionMatches(true, 0, charsetHeader, 0, charsetHeader.length())) {
                String charset = StringUtil.substringAfter(headerContentType[crank], '=');
                if (charset != null) {
                    return new String[] {"--" + boundary, charset};
                }
            }
            return new String[] {"--" + boundary};
        }
        return null;
    }

    @Override
    public boolean isMultipart() {
        return decoder.isMultipart();
    }

    @Override
    public void setDiscardThreshold(int discardThreshold) {
        decoder.setDiscardThreshold(discardThreshold);
    }

    @Override
    public int getDiscardThreshold() {
        return decoder.getDiscardThreshold();
    }

    @Override
    public List<InterfaceHttpData> getBodyHttpDatas() {
        return decoder.getBodyHttpDatas();
    }

    @Override
    public List<InterfaceHttpData> getBodyHttpDatas(String name) {
        return decoder.getBodyHttpDatas(name);
    }

    @Override
    public InterfaceHttpData getBodyHttpData(String name) {
        return decoder.getBodyHttpData(name);
    }

    @Override
    public InterfaceHttpPostRequestDecoder offer(HttpContent content) {
        return decoder.offer(content);
    }

    @Override
    public boolean hasNext() {
        return decoder.hasNext();
    }

    @Override
    public InterfaceHttpData next() {
        return decoder.next();
    }

    @Override
    public InterfaceHttpData currentPartialHttpData() {
        return decoder.currentPartialHttpData();
    }

    @Override
    public void destroy() {
        decoder.destroy();
    }

    @Override
    public void cleanFiles() {
        decoder.cleanFiles();
    }

    @Override
    public void removeHttpDataFromClean(InterfaceHttpData data) {
        decoder.removeHttpDataFromClean(data);
    }

    /**
     * Split the very first line (Content-Type value) in 3 Strings
     *
     * @return the array of 3 Strings
     */
    private static String[] splitHeaderContentType(String sb) {
        int aStart;
        int aEnd;
        int bStart;
        int bEnd;
        int cStart;
        int cEnd;
        aStart = HttpPostBodyUtil.findNonWhitespace(sb, 0);
        aEnd =  sb.indexOf(';');
        if (aEnd == -1) {
            return new String[] {sb, "", ""};
        }
        bStart = HttpPostBodyUtil.findNonWhitespace(sb, aEnd + 1);
        if (sb.charAt(aEnd - 1) == ' ') {
            aEnd--;
        }
        bEnd =  sb.indexOf(';', bStart);
        if (bEnd == -1) {
            bEnd = HttpPostBodyUtil.findEndOfString(sb);
            return new String[] {sb.substring(aStart, aEnd), sb.substring(bStart, bEnd), ""};
        }
        cStart = HttpPostBodyUtil.findNonWhitespace(sb, bEnd + 1);
        if (sb.charAt(bEnd - 1) == ' ') {
            bEnd--;
        }
        cEnd = HttpPostBodyUtil.findEndOfString(sb);
        return new String[] {sb.substring(aStart, aEnd), sb.substring(bStart, bEnd), sb.substring(cStart, cEnd)};
    }

}
```

```
/**
 * copy of HttpPostRequestDecoder to fix
 * https://github.com/netty/netty/issues/10281
 */
public class BlynkHttpPostMultipartRequestDecoder extends HttpPostMultipartRequestDecoder {

    private final boolean state;

    public BlynkHttpPostMultipartRequestDecoder(HttpDataFactory factory, HttpRequest request, Charset charset) {
        super(factory, request, charset);
        this.state = true;
    }

    @Override
    public HttpPostMultipartRequestDecoder offer(HttpContent content) {
        //this is very dirty hack
        //we skip the first invocation of the offer
        //it wont work for every case, but we have Aggregate handler in the pipeline
        //so we are covered here :)
        if (state) {
            return super.offer(content);
        }
        return null;
    }
}
```

**Comment by 88250** [comment]
Hello, I still encountered this problem on `v4.1.60.Final`, please check it, thanks.

**Comment by 88250** [comment]
FYI, this problem no longer exists in `v4.1.73.Final`.

**Comment by doom369** [comment]
No longer valid
