### ISSUE TITLE
Recycler could cache infinite resources

### ISSUE THREAD

**Issue by ylgrgyq** [netty/netty#3166]
In Netty.4.0.24.final.

In class io.netty.util.Recycler, there's a DEFAULT_MAX_CAPACITY variable to constrain the size of the stack in Recycler. From INITIAL_CAPACITY, whenever the stack is full, it's size doubled until hitting the DEFAULT_MAX_CAPACITY limit(Line 341 in Netty.4.0.24.final). 
![image](https://cloud.githubusercontent.com/assets/1115061/5156597/45b7fa9a-730a-11e4-89aa-bb1f87c47428.png)
As you can see in the image above, stack size is constrained by maxCapacity. And if the size > maxCapacity, this check will fail forever, beacuse the check use "if (size == maxCapacity)" rather than "if (size > maxCapacity)".  And there's a way to set size bigger than maxCapacity.

In class WeakOrderQueue which is an inner class in Recycler, there's a method called "transfer" which can also double the stack size in Recycler, but there's no check to ensure the stack size not exceed DEFAULT_MAX_CAPACITY limit(Line 218 in Netty.4.0.24.final) like the one mentioned before. 
![image](https://cloud.githubusercontent.com/assets/1115061/5156598/5a17c01a-730a-11e4-873b-1e65ee539db3.png)
In the image above, variable "to" is a stack in Recycler and count is resources's quantity recycled by other thread rather than the Recycler's owner. If there's no enough space for those resources to be recycled, the stack's size will be doubled. I think there should have a check for the stack size here. And whenever the stack size greater than maxCapacity, it can grow infinitely.

**Comment by ninja-** [comment]
@trustin do you think there is still something related in Recycler to be fixed since you guys are bumping the milestone?

**Comment by trustin** [comment]
@ninja- I believe we have addressed this issue in #3203 and a9fda3c8e0b20a1a3da0353c033cb57be7ad49b2. I'm not sure this is the problem you are experiencing, though, because I didn't follow the discussion between you and @normanmaurer. Maybe @normanmaurer can answer better than I.

@tea-dragon Do you still experience this issue?

**Comment by ninja-** [comment]
@trustin personally I am fine with the current state of the recycler in .30, the only thing I am wondering about is what did increase _the need for buffers at the same time_ growing the recycler in .30. could it be because I recently added tcp_nodelay? (not considering it a bug, but I am tweaking down the maximum recycler's amount so it would stay clean when the proxy is empty)

**Comment by Iceee** [comment]
@ninja- I'm not sure updating netty will fix this since it's a netty implementation issue on BungeeCord's side. Along with the changes I made above, I also updated to the latest netty. I don't remember that fixing the issue on its own.

**Comment by ninja-** [comment]
@Iceee yes, your patch didn't fix the problem by itself. It's fixed in netty .25+ while upstream bungee keeps using .24

**Comment by Iceee** [comment]
@ninja- I'm not sure updating netty alone will fix this since it's a netty implementation issue on BungeeCord's side. Along with the changes I made above, I also updated to the latest netty. I don't remember that fixing the issue on its own. 

There may be a netty bug in regards to recycling entries on closed connections, but this issue specifically stems from BungeeCord not properly implementing netty, and therefore netty blindly writing to buffers that are growing to unlimited sizes.

**Comment by ninja-** [comment]
@Iceee there wasn't any error in bungee's implementation. your patch in fact did nothing and didn't stop the infinity bug from eating majority of ram when randomly triggered so there was no difference

**Comment by Iceee** [comment]
@ninja- Actually, it fixed everyone's problem as you can read in the issue!

**Comment by Scottmitch** [comment]
@Iceee @ninja- - There should be some bound on data that is written when the channel is not writable (as Iceee/BungeeCord@1a997bf appears to do). However it looks like your are dropping data in this case (not sure if this is a problem for you), and also leaking buffers (write will call `release` on the buffer, but since you are not writing it `release` will not be called).  So it seems like you need both the "not writing too much" concept and `Recycler` bug (fixed in 4.0.25).

**Comment by ninja-** [comment]
@Iceee well I remember @md-5 comment about the patch that it only reduced leak's severity and not fixed it...sure it's a good thing to have this check along with Recycler fix and that's what I personally did.

@Scottmitch it's interesting what you say about release() but I am pretty sure it _couldn't_ leak a buffer via refcnt in any case. have you seen HandlerBoss#channelRead? 

Regarding data dropping it shouldn't be a problem because if connections were to lag that much they wouldn't be a working connection anyway so it doesn't matter(I would rather close such connections just like the timeout check does..)

**Comment by Scottmitch** [comment]
> have you seen HandlerBoss#channelRead?

@ninja- - No. My leak assessment is based upon the `write` method modified by Iceee/BungeeCord@1a997bf in isolation. The contract for the `write(Object o)` method appears to assume ownership / release responsibility of the parameter. This method provides no return status or indication if the write was actually done so I'm not sure how a caller of this method could reliably know if a write was done or not, and thus release the buffer after this method call if needed.

> (I would rather close such connections just like the timeout check does

If you use case permits this behavior that is great...nice and simple. However keep in mind these conditions may fluctuate (according to the transport you use, networking conditions, and other environmental factors).

**Comment by ninja-** [comment]
@Scottmitch I would assume that write() would release the object even if it _denied_ the channel write (that would be a good api design for this case, checking futures for every write would be an overhead). But there shouldn't be _currently_ such a case given isWritable() check, right?

**Comment by Scottmitch** [comment]
It seems there is some confusion, let me clarify:

[Channel.write](https://github.com/netty/netty/blob/master/transport/src/main/java/io/netty/channel/Channel.java#L446) (the interface and Netty implementations) will ensure `release()` is called on any [ReferenceCounted](https://github.com/netty/netty/blob/master/common/src/main/java/io/netty/util/ReferenceCounted.java) object after it is completely written.

[ChannelWrapper.write(..)](https://github.com/SpigotMC/BungeeCord/blob/master/proxy/src/main/java/net/md_5/bungee/netty/ChannelWrapper.java#L41) and Iceee/BungeeCord@1a997bf both may have a leak if the `Object packet` parameter is (or contains) a [ReferenceCounted](https://github.com/netty/netty/blob/master/common/src/main/java/io/netty/util/ReferenceCounted.java), because there is a condition for which they don't call `Channel.write(..)`, and are also not calling `packet.release()`.  I'm not sure of the usage pattern (if/when this conditional clause will evaluate to false) but if/when the conditional evaluates to false does there will be a leak.

> release the object even if it denied the channel write

What do you mean by `denied`?  Hopefully my first statement clarified any confusion regarding the `Channel.write(..)` interface?

> But there shouldn't be currently such a case given isWritable() check, right?

You are more likely to leak buffers by adding the `isWritable()` check because the conditional is more likely to evaluate to false, and thus you aren't calling `Channel.write()`.

**Comment by ninja-** [comment]
@Scottmitch you are right about this part, sorry. let me see if this will fix the leaks on production?

**Comment by Scottmitch** [comment]
> but are you sure you are evaluating Iceee's code in context of the HandlerBoss...? these write() calls always happen during channelRead and the buffers are always .released() at the end @ HandlerBoss

Based upon a quick glance calls to `ChannelWrapper.write(..)` from `HandlerBoss.channelRead(..)` should not leak based upon the following:

When `ChannelWrapper.write(..)` encounters a `PacketWrapper` it [marks it as released](https://github.com/SpigotMC/BungeeCord/blob/81d1c46a0dd5505ab8b78c1f54b13f5353e36b41/proxy/src/main/java/net/md_5/bungee/netty/ChannelWrapper.java#L45) before passing the buffer to `write`.  For the `PacketWrapper` type this will ensure it is released 1 time either in `ChannelWrapper.write(..)` or [HandlerBoss.channelRead(..)](https://github.com/SpigotMC/BungeeCord/blob/master/proxy/src/main/java/net/md_5/bungee/netty/HandlerBoss.java#L88) because [PacketWrapper.trySingleRelease()](https://github.com/SpigotMC/BungeeCord/blob/master/protocol/src/main/java/net/md_5/bungee/protocol/PacketWrapper.java) checks if it is "released" before calling `buf.release()`.

A few followup questions:
- if [handler != null](https://github.com/SpigotMC/BungeeCord/blob/master/proxy/src/main/java/net/md_5/bungee/netty/HandlerBoss.java#L66) is false more analysis is needed to see if there is a leak.
- Are all calls to `ChannelWrapper.write(..)`? always from `HandlerBoss.channelRead(..)`?
- How does `ChannelWrapper.write(..)` coordinate release of objects which are [not of type PacketWrapper](https://github.com/SpigotMC/BungeeCord/blob/81d1c46a0dd5505ab8b78c1f54b13f5353e36b41/proxy/src/main/java/net/md_5/bungee/netty/ChannelWrapper.java#L49) when a `ch.write` does not occur?

An an unrelated note....I think you also mentioned no copy operations were being done before. Not sure if this code is run in production but there is a copy done in [MinecraftDecoder](https://github.com/SpigotMC/BungeeCord/blob/9cf57ca929934fb58463a1e654e81ec72451d894/protocol/src/main/java/net/md_5/bungee/protocol/MinecraftDecoder.java#L24)

**Comment by ninja-** [comment]
@Scottmitch in my own version I removed all .copy() but the problem but the $Entry problem also appears there.

Regarding your questsions about releasing the buffer, I have added 
```
inally
            {
                ByteBuf b = packet.getBuffer();
                packet.trySingleRelease();

                if (b != null && b.refCnt() > 0) {
                    BungeeCord.getInstance().getLogger().log(Level.SEVERE, "Packet leaked while hadling for " + handler + ": " + packet + ", " + b.refCnt() + " refs!!!");

                }
            }
```
it's always 0 + netty leak detector is silent, isn't that enough proof that the .release() mechanism works correctly here?

**Comment by Scottmitch** [comment]
> it's always 0 + netty leak detector is silent, isn't that enough proof that the .release() mechanism works correctly here?

@ninja- - I gave a pretty detailed analysis in https://github.com/netty/netty/issues/3166#issuecomment-135304391 and came to the conclusion for what appears to be the "common" case there should not be any buffer leaks (with some followup questions and caveats). 

Can you try to use the [UnpooledByteBufAllocator](https://github.com/netty/netty/blob/master/buffer/src/main/java/io/netty/buffer/UnpooledByteBufAllocator.java#L28)?  I did a quick check and I don't see any `Recycler` being used.

**Comment by ninja-** [comment]
@Scottmitch great idea I'll try the allocator.

**Comment by ninja-** [comment]
> How does ChannelWrapper.write(..) coordinate release of objects which are not of type PacketWrapper when a ch.write does not occur?

they aren't released because they aren't detained so the balance stays the same (0)

**Comment by ninja-** [comment]
1:        597079       42989688  io.netty.buffer.UnpooledUnsafeDirectByteBuf
   6:        597080       19106560  java.nio.DirectByteBuffer$Deallocator
   4:        597081       23883240  sun.misc.Cleaner
   3:        597088       38213632  java.nio.DirectByteBuffer
   2:        597089       38213696  io.netty.channel.ChannelOutboundBuffer$Entry
   5:        597378       19116096  io.netty.util.Recycler$DefaultHandle

3 minutes with unpooled allocator...

**Comment by Scottmitch** [comment]
> they aren't released because they aren't detained so the balance stays the same (0)

Can you clarify? Do mean to say the are never of type `ReferenceCounted` in this case?

> 3 minutes with unpooled allocator...

Sry...just found a few more RECYCLERs being used. Have you done a heap dump analysis? Can you tell me what the "strong" GC root references to the `UnpooledUnsafeDirectByteBuf` are (just a few samples)

**Comment by ninja-** [comment]
1. They output buffers are normally detained/released by other handler such as decoders etc. and the app only needs to keep it's balance to zero.

2. yeah the only strong ref to DirectByteBuf is Recycler$DefaultHandle via OutboundBuffer$Entry

**Comment by ninja-** [comment]
weird, when looking at the heap dump the DirectByteBufs are gone.
just the io.netty.channel.ChannelOutboundBuffer$Entry leaking - 3 million of them.

**Comment by ninja-** [comment]
@Scottmitch I think that I know what's wrong with netty's recycler. but first, I can't get netty debug to print. how do I turn it on from the start?

**Comment by normanmaurer** [comment]
@ninja- you mean enable debug logging from the start ?

**Comment by ninja-** [comment]
yeah
    static {
        InternalLoggerFactory.setDefaultFactory(new JdkLoggerFactory());
        Logger.getGlobal().setLevel(Level.ALL);
        Logger.getLogger("io.netty").setLevel(Level.ALL);
    }

doesnt do much

**Comment by normanmaurer** [comment]
@ninja- you have a logging.properties file that tells where to log ?

**Comment by ninja-** [comment]
@normanmaurer no, is it for the java logger?

**Comment by normanmaurer** [comment]
@ninja- yes... that said I never used jdk logger. Anyway here seems to be an example:
http://stackoverflow.com/questions/960099/how-to-set-up-java-logging-using-a-properties-file-java-util-logging

**Comment by ninja-** [comment]
@normanmaurer  :\ I was looking at wrong property because I was checking out on master and they differ. so it ignored my property...

**Comment by Scottmitch** [comment]
> So that was my problem...the property to change recycler settings differs in master and netty 4.0. I would guess it should work correctly now.

@ninja- Can you clarify? Are you saying you are no longer believe there is a leak in `Recycler`, and the behavior you are seeing was just the `maxCapacity` was configured to be to high?

**Comment by ninja-** [comment]
@Scottmitch yup.
it changed from
```
 int maxCapacity = SystemPropertyUtil.getInt("io.netty.recycler.maxCapacity.default", 0);
```
to
```
 int maxCapacity = SystemPropertyUtil.getInt("io.netty.recycler.maxCapacity", 0);
```

and I never expected this

**Comment by Scottmitch** [comment]
@ninja- - Yes that is unfortunate :( 9fe9710315bb89b015a3de0fbf4c1019a10e5c85

@tea-dragon - Would you mind providing a re-producer? We may want to move the discussion to another issue too...

**Comment by aikar** [comment]
Maybe a more sane Recycler default capacity could be implemented? Why in the world is it so high anyways? 

Pool reasonably low then let people tweak higher if they really believe itll help their application.

**Comment by ninja-** [comment]
@aikar you don't want this trust me...don't deploy it on prod

**Comment by aikar** [comment]
@ninja- what do you mean?
Are you saying limiting the recycler is bad? I really hope that something isn't depending on a super large object pool.

Surely 5k instances of something should be enough to handle per thread...

**Comment by ninja-** [comment]
@aikar I spent few months fixing this...take patches from my branch and it will be down to ~300

**Comment by Scottmitch** [comment]
can we move discussion to https://github.com/netty/netty/issues/4146?

@ninja- - I thought the issues you were observing related to this issue were because of setting the wrong system property https://github.com/netty/netty/issues/3166#issuecomment-135485992? Lets open a new issue if there are other issues...becomes too tough to track otherwise.

**Comment by ninja-** [comment]
@Scottmitch there's no issues right now really as I am trying to explain this to @aikar...

**Comment by aikar** [comment]
I understand that, I just noticed discussion on the maxCapacity setting that was used to I'm assuming to minimize impact that this issue was rising, and I was stating a desire for a more sane limit. As regardless of the underlying issues being fixed or not, it still makes sense for a sane limit for future cases that could cause the recycler to grow large for a temporary spike.

But I see now there is another issue open about better limits, so all is good and can discuss there.

**Comment by ninja-** [comment]
the current 266k*threads limit is sane...unless you want to allocate 200mb to java and have 1000% cpu usage

**Comment by normanmaurer** [comment]
I think we added a lot of things to be able to specify max limits etc. So we can close this now

**Comment by lqbilbo** [comment]
Thanks!I have solved the problem of large size in oldgen by the issue
