### ISSUE TITLE
Netty 4.1.0.Final : IllegalStateException: executor not accepting a task

### ISSUE THREAD

**Issue by lburgazzoli** [netty/netty#5313]
I have a test in an application that check for proper release of promises upon shutdown that was workig as expected with 4.1.0.CR7 but not more on 4.1.0.Final, I've isolated Netty's code from the application :

```java
  @Test
  public void test() throws Exception {
    NioEventLoopGroup eventLoopGroup = new NioEventLoopGroup();

    Bootstrap bootstrap = new Bootstrap()
      .group(eventLoopGroup)
      .channel(NioSocketChannel.class)
      .option(ChannelOption.ALLOCATOR, PooledByteBufAllocator.DEFAULT)
      .option(ChannelOption.TCP_NODELAY, true)
      .option(ChannelOption.CONNECT_TIMEOUT_MILLIS, 300)
      .resolver(new DnsAddressResolverGroup(
        NioDatagramChannel.class,
        DnsServerAddresses.defaultAddresses()))
      .handler(new ChannelInitializer<SocketChannel>() {
        @Override
        public void initChannel(SocketChannel ch) throws Exception {
          ChannelPipeline p = ch.pipeline();
          p.addLast("codec", new HttpClientCodec());
          p.addLast("chunkedWriter", new ChunkedWriteHandler());
          p.addLast("aggregate", new HttpObjectAggregator(1024 * 100));
        }
      });

    final ChannelFuture cf = bootstrap.connect(InetSocketAddress.createUnresolved("localhost",4001));
    final Promise<Object> p = cf.channel().eventLoop().newPromise();

    cf.addListener((ChannelFuture f) -> {
      if (f.isSuccess()) {
        p.setSuccess("Success");
      } else {
        p.setFailure(f.cause());
      }
      
      f.channel().close();
    });

    eventLoopGroup.shutdownGracefully();

    p.await();
  }
```

If I run it with Netty 4.1.0.Final, the test never ends blocking on ```p.await()``` and an exception is thrown:

```
[nioEventLoopGroup-2-1] [WARN] io.netty.util.concurrent.DefaultPromise - An exception was thrown by io.netty.bootstrap.Bootstrap$1.operationComplete()
java.lang.IllegalStateException: executor not accepting a task
	at io.netty.resolver.AddressResolverGroup.getResolver(AddressResolverGroup.java:58)
	at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:198)
	at io.netty.bootstrap.Bootstrap.access$000(Bootstrap.java:50)
	at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:187)
	at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:173)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:559)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:533)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersWithStackOverFlowProtection(DefaultPromise.java:454)
	at io.netty.util.concurrent.DefaultPromise.access$100(DefaultPromise.java:36)
	at io.netty.util.concurrent.DefaultPromise$4.run(DefaultPromise.java:442)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:339)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:374)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:145)
	at java.lang.Thread.run(Thread.java:745)
```

When running with CR7, the test ends properly and without any warning.

**Comment by normanmaurer** [comment]
Will check

**Comment by normanmaurer** [comment]
Ok I think I know what the problem is... working on it

**Comment by taojiaenx** [comment]
@lburgazzoli Maybe the reason is that you have shutdown the EventPool and all SingleThreadeventLoops are closed And if you add a new task, there whill be an IllegalStateException.I

**Comment by normanmaurer** [comment]
Yep this is the issue... That said we need to notify the promise. I have a fix in the works for this.

**Comment by normanmaurer** [comment]
Should be fixed by https://github.com/netty/netty/pull/5339

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/5339

**Comment by rahuls6** [comment]
We still see this issue in 4.1.33. Any updates on this ?

**Comment by johnou** [comment]
@rahuls6 can you provide a reproducer?

**Comment by james-r-smith** [comment]
I am still having this issue with my client socket connection. The disconnection is triggered from REST API. I will try to provide as much as I can. If more information is needed to track this, I can try to provide a small program as well. I'm hoping this can be caught. 🤞 

### Bootstrap configuration

```java
public class NettyDeviceFactory {

  private Connection bootstrap() {
      final Bootstrap bootstrap = new Bootstrap()
              .group(new NioEventLoopGroup(1))
              .channel(NioSocketChannel.class)
              .remoteAddress({{REDACTED}})
              .option(ChannelOption.SO_KEEPALIVE, true);
      requestBootstrap.handler(new ChannelInitializer<SocketChannel>() {
          @Override
          protected void initChannel(final SocketChannel ch) {
              ch.pipeline().addLast({{REDACTED}});
          }
      });

      return new NettyConnection(createReconnectListener(bootstrap));
  }

  private ReconnectListener createReconnectListener(final Bootstrap bootstrap) {
      return new ReconnectListener({{REDACTED}});
  }

}
```

### Disconnection logic

```java
public class NettyConnection {
  
  public void connect() {
    bootstrap.connect().addListener(reconnectListener);
  }

  public void disconnect() {
      bootstrap.config().group().shutdownGracefully();
  }

}
```

### Reconnection logic

```java
public class ReconnectListener implements ChannelFutureListener {

  private void scheduleReconnect(final ChannelFuture future) {
      future.channel().eventLoop().schedule(() -> {
          bootstrap.connect().addListener(this);
      }, reconnectDelayTimeNanos, TimeUnit.NANOSECONDS);
  }

  private void reconnectOnClose(final ChannelFuture future) {
      future.channel().closeFuture().addListener((ChannelFuture cf) -> {
          bootstrap.connect().addListener(this);
      });
  }

  @Override
  public void operationComplete(final ChannelFuture future) {
      if (!future.isSuccess()) {
          future.cause().printStackTrace();
          scheduleReconnect(future);
      } else {
          reconnectOnClose(future);
      }
  }

}
```

### Stack trace

```
java.lang.IllegalStateException: executor not accepting a task
	at io.netty.resolver.AddressResolverGroup.getResolver(AddressResolverGroup.java:60) ~[netty-all-4.1.35.Final.jar:4.1.35.Final]
	at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:200) ~[netty-all-4.1.35.Final.jar:4.1.35.Final]
	at io.netty.bootstrap.Bootstrap.doResolveAndConnect(Bootstrap.java:170) ~[netty-all-4.1.35.Final.jar:4.1.35.Final]
	at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:119) ~[netty-all-4.1.35.Final.jar:4.1.35.Final]
	at {{REDACTED}}
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:502) ~[netty-all-4.1.35.Final.jar:4.1.35.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:476) ~[netty-all-4.1.35.Final.jar:4.1.35.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:415) ~[netty-all-4.1.35.Final.jar:4.1.35.Final]
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:540) ~[netty-all-4.1.35.Final.jar:4.1.35.Final]
	at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:529) ~[netty-all-4.1.35.Final.jar:4.1.35.Final]
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:101) ~[netty-all-4.1.35.Final.jar:4.1.35.Final]
	at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84) ~[netty-all-4.1.35.Final.jar:4.1.35.Final]
	at io.netty.channel.AbstractChannel$CloseFuture.setClosed(AbstractChannel.java:1183) ~[netty-all-4.1.35.Final.jar:4.1.35.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.doClose0(AbstractChannel.java:769) ~[netty-all-4.1.35.Final.jar:4.1.35.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:745) ~[netty-all-4.1.35.Final.jar:4.1.35.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:616) ~[netty-all-4.1.35.Final.jar:4.1.35.Final]
	at io.netty.channel.nio.NioEventLoop.closeAll(NioEventLoop.java:730) ~[netty-all-4.1.35.Final.jar:4.1.35.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:509) ~[netty-all-4.1.35.Final.jar:4.1.35.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906) ~[netty-all-4.1.35.Final.jar:4.1.35.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-all-4.1.35.Final.jar:4.1.35.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-all-4.1.35.Final.jar:4.1.35.Final]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_131]
```

**Comment by normanmaurer** [comment]
@james-r-smith this means you already shutdown the `EventLoopGroup`.

**Comment by james-r-smith** [comment]
@normanmaurer, okay. So, where I see it happening is when I successfully connect, which then calls `reconnectOnClose(future);` in `ReconnectListener`. So, I notice now that my method tries to reconnect on close `bootstrap.connect().addListener(this);`. This could be a problem when the `EventLoopGroup` is already closed. Makes sense. Any way I can do a check on the `EventLoopGroup` within that lambda?
