### ISSUE TITLE
error:140D00CF:SSL routines:SSL_write:protocol is shutdown = memory leak?

### ISSUE THREAD

**Issue by rkapsi** [netty/netty#6249]
We're currently running a 4.1.7.Final-SNAPSHOT version of Netty that pre-dates the official 4.1.7.Final release (our SNAPSHOT is roughly from January 6, 2017).

We today attempted a release with 4.1.8.Final-SNAPSHOT and I've tried 4.1.7.Final as well. There is suddenly a large number of the following (new) Exceptions and the server runs out of memory quickly until Linux's oom_killer steps in and axes the process. There are no Java OOMEs nor do YourKit memory snapshots show anything out of the ordinary which points towards direct memory being leaked.

Looking the recent commit history there appears to be this dd055c01c78c3a6ce5b9195890486a6e1ab072d2 change that is potentially related (happened after January 6 but before 4.1.7.Final release).

```java
javax.net.ssl.SSLException: error:140D00CF:SSL routines:SSL_write:protocol is shutdown
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.shutdownWithError(ReferenceCountedOpenSslEngine.java:719) ~[netty-all-4.1.7.Final.jar:4.1.7.Final]
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.shutdownWithError(ReferenceCountedOpenSslEngine.java:708) ~[netty-all-4.1.7.Final.jar:4.1.7.Final]
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.wrap(ReferenceCountedOpenSslEngine.java:685) ~[netty-all-4.1.7.Final.jar:4.1.7.Final]
	at javax.net.ssl.SSLEngine.wrap(SSLEngine.java:509) ~[?:1.8.0_102]
	at io.netty.handler.ssl.SslHandler.wrap(SslHandler.java:746) ~[netty-all-4.1.7.Final.jar:4.1.7.Final]
	at io.netty.handler.ssl.SslHandler.wrap(SslHandler.java:578) ~[netty-all-4.1.7.Final.jar:4.1.7.Final]
	at io.netty.handler.ssl.SslHandler.wrapAndFlush(SslHandler.java:550) ~[netty-all-4.1.7.Final.jar:4.1.7.Final]
	at io.netty.handler.ssl.SslHandler.flush(SslHandler.java:531) ~[netty-all-4.1.7.Final.jar:4.1.7.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:777) [netty-all-4.1.7.Final.jar:4.1.7.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:769) [netty-all-4.1.7.Final.jar:4.1.7.Final]
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:750) [netty-all-4.1.7.Final.jar:4.1.7.Final]
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.flush(CombinedChannelDuplexHandler.java:530) [netty-all-4.1.7.Final.jar:4.1.7.Final]
	at io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:115) [netty-all-4.1.7.Final.jar:4.1.7.Final]
	at io.netty.channel.CombinedChannelDuplexHandler.flush(CombinedChannelDuplexHandler.java:355) [netty-all-4.1.7.Final.jar:4.1.7.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:777) [netty-all-4.1.7.Final.jar:4.1.7.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:769) [netty-all-4.1.7.Final.jar:4.1.7.Final]
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:750) [netty-all-4.1.7.Final.jar:4.1.7.Final]
	at io.netty.channel.ChannelDuplexHandler.flush(ChannelDuplexHandler.java:117) [netty-all-4.1.7.Final.jar:4.1.7.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:777) [netty-all-4.1.7.Final.jar:4.1.7.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:769) [netty-all-4.1.7.Final.jar:4.1.7.Final]
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:750) [netty-all-4.1.7.Final.jar:4.1.7.Final]
	at io.netty.channel.ChannelDuplexHandler.flush(ChannelDuplexHandler.java:117) [netty-all-4.1.7.Final.jar:4.1.7.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:777) [netty-all-4.1.7.Final.jar:4.1.7.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:769) [netty-all-4.1.7.Final.jar:4.1.7.Final]
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:750) [netty-all-4.1.7.Final.jar:4.1.7.Final]
	at io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:115) [netty-all-4.1.7.Final.jar:4.1.7.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:777) [netty-all-4.1.7.Final.jar:4.1.7.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:769) [netty-all-4.1.7.Final.jar:4.1.7.Final]
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:750) [netty-all-4.1.7.Final.jar:4.1.7.Final]
	at io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:115) [netty-all-4.1.7.Final.jar:4.1.7.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:777) [netty-all-4.1.7.Final.jar:4.1.7.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:769) [netty-all-4.1.7.Final.jar:4.1.7.Final]
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:750) [netty-all-4.1.7.Final.jar:4.1.7.Final]
	at io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:115) [netty-all-4.1.7.Final.jar:4.1.7.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:777) [netty-all-4.1.7.Final.jar:4.1.7.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:769) [netty-all-4.1.7.Final.jar:4.1.7.Final]
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:750) [netty-all-4.1.7.Final.jar:4.1.7.Final]
	at io.netty.channel.ChannelDuplexHandler.flush(ChannelDuplexHandler.java:117) [netty-all-4.1.7.Final.jar:4.1.7.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:777) [netty-all-4.1.7.Final.jar:4.1.7.Final]
...
```

**Comment by rkapsi** [comment]
I forgot to mention that I tried to run it with `-Dio.netty.noPreferDirect=true"` and `-Dio.netty.allocator.type=unpooled"` which doesn't make a difference.

**Comment by doom369** [comment]
@rkapsi you also need to turn openssl off in order to avoid leak. I think @normanmaurer will update us regarding those tickets soon.

**Comment by rkapsi** [comment]
In our case not really an option. Our product depends on it but I can thankfully continue using the working version of Netty in the meantime.

**Comment by Scottmitch** [comment]
@rkapsi - Can you try to run with https://github.com/netty/netty/pull/6238 ? There was a bug in the commit you referenced [removed a call to shutdown](https://github.com/netty/netty/commit/dd055c01c78c3a6ce5b9195890486a6e1ab072d2#diff-cfd417915faad637e4278b54adafd9baL551) in error.

**Comment by rkapsi** [comment]
@Scottmitch will do tomorrow first thing in the morning (NYC time).

**Comment by normanmaurer** [comment]
@rkapsi the exception is fixed by https://github.com/netty/netty/pull/6238 ... Will have another PR this morning to test with.

**Comment by normanmaurer** [comment]
@rkapsi PTAL at https://github.com/netty/netty/pull/6252 as well.

**Comment by rkapsi** [comment]
@normanmaurer confirm, this fixes the Exception. Stay tuned regards the memory problem. It appears #6252 **does not** fix it.

This is how one of our graphs looked like: https://i.imgsafe.org/0d77f1a4e6.png

I was wrong regards the SNAPSHOT version we use (the one that works). It's a build from January 9. I have a few more builds I can try.

**Comment by normanmaurer** [comment]
@rkapsi can I have a heap dump?

**Comment by rkapsi** [comment]
Unfortunately no. It contains sensitive PKI material. If you have a hunch, class names etc. then let me know. I can poke around and share screenshots and numbers.

I've just double checked #6252 with a second build. The leak persists. The graph from above show's Linux's free memory (e.g. the value that's shown in `top`). As you can see it drops from ~12GB down to almost nothing. Our JVM heap is configured to be 4GB and the heap dump is only 2.3GB. So clearly something outside the JVM heap.

**Comment by normanmaurer** [comment]
@rkapsi bummer... maybe ChannelOutboundBuffer.Entry instances. Would be interested to see what ByteBuf instances are in there and what there indices + capacity are.

**Comment by normanmaurer** [comment]
@rkapsi also if you can give me any idea which builds worked and which started to show this would help

**Comment by rkapsi** [comment]
https://i.imgsafe.org/0ed39effb0.png
https://i.imgsafe.org/0ed437aecf.png

OK: netty-all-4.1.7.Final-20170109.120749-87 (the version we use)
OK: netty-all-4.1.7.Final-20170110.120845-88
OK: netty-all-4.1.7.Final-20170111.122656-89 (last build I have)

So it's something after January 11. Going to cut releases from commits as next.

**Comment by normanmaurer** [comment]
@rkapsi ok thanks... keep me posted

**Comment by rkapsi** [comment]
I forgot to say, the second screenshot shows only one Entry/ByteBuf expanded but the values are the same for the others (max capacity and writer index are 65k).

**Comment by normanmaurer** [comment]
@rkapsi also can you tell me if its direct memory or heap memory that cause the problem ? And also what are the objects that take most space in the heap dump ?

**Comment by rkapsi** [comment]
By Object: https://i.imgsafe.org/0f22ec87c3.png
By Size: https://i.imgsafe.org/0f2335cb22.png

I'd be direct memory that causes the problem. Our JVM heap is configured to be 4GB and the dump file is only 2.3GB and YourKit says 1.8GB is effectively in use.

**Comment by rkapsi** [comment]
Alright, found the commit: https://github.com/netty/netty/commit/be8c16cd0c54f9013b539741bf2a1db13ddc0126

We do use mutual TLS but I don't quite understand what's happening there.

Memory usage after each deploy: https://i.imgsafe.org/109d30b4c9.png
Normal memory: https://i.imgsafe.org/109dd92c71.png
Bad memory: https://i.imgsafe.org/109d838047.png

**Comment by normanmaurer** [comment]
@rkapsi thanks a lot... Not sure how this could lead to this but I will have a look shortly!

**Comment by normanmaurer** [comment]
@rkapsi talking with @Scottmitch atm... @Scottmitch may be on something... will keep you posted

**Comment by normanmaurer** [comment]
@rkapsi also is it correct to assume that you create / destroy a lot of ReferenceCountedOpenSslServerContext instances ?

**Comment by Scottmitch** [comment]
@rkapsi - Thanks for the commit reference ... I think I found a potential leak https://github.com/netty/netty-tcnative/pull/220 .. I'm going to run Netty tests now but can you try this?

**Comment by rkapsi** [comment]
@normanmaurer yes we do. Possibly by the millions per day.

**Comment by rkapsi** [comment]
@Scottmitch excellent. Do you publish nightly SNAPSHOTs of tcnative anywhere? We depend on the linux-x86_64-fedora artifact and I have no easy way to build it.

**Comment by normanmaurer** [comment]
@rkapsi we do on oss.sonatype.org but not for PRs. Should I send you the jars via email ?

**Comment by rkapsi** [comment]
@normanmaurer ok, that works - rkapsi at geeemail dot com

**Comment by Scottmitch** [comment]
I will re-open until we verify there are no other issues.

**Comment by normanmaurer** [comment]
@Scottmitch shouldnt we wait until @rkapsi verified it before closing it ?

**Comment by Scottmitch** [comment]
(it closed automatically bcz the tcnative commit referenced this issue)

**Comment by normanmaurer** [comment]
lol... You beat me by a few secs ;)

**Comment by normanmaurer** [comment]
@rkapsi you have mail :)

**Comment by rkapsi** [comment]
Testing...

**Comment by normanmaurer** [comment]
Thx!

**Comment by rkapsi** [comment]
@normanmaurer @Scottmitch victory! thx gentleman.

**Comment by Scottmitch** [comment]
great ... thanks for verifying!

Fixed by https://github.com/netty/netty-tcnative/pull/220

**Comment by normanmaurer** [comment]
Awesome!

**Comment by doom369** [comment]
@normanmaurer does adding tcnative-snapshot would be enough? Or I should also rebuild netty with it in order to apply this patch?

**Comment by normanmaurer** [comment]
@doom369 just the snapshot... That said I just released netty-tcnative-1.1.33.Fork26 which includes the fix. Just waiting for maven central to sync before update the version in netty.

**Comment by doom369** [comment]
@normanmaurer thanks, super. As I just reproduced same behaviour on small prod instance.

**Comment by normanmaurer** [comment]
@doom369 already its on maven central now... See also: https://github.com/netty/netty/pull/6259

**Comment by rkapsi** [comment]
@normanmaurer FYI: I have now moved to 4.1.8-SNAPSHOT and Fork26. Things are good but that shutdown exception is still happening (but at a much lower velocity).

```java
 javax.net.ssl.SSLException: error:140D00CF:SSL routines:SSL_write:protocol is shutdown
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.shutdownWithError(ReferenceCountedOpenSslEngine.java:745) ~[netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.shutdownWithError(ReferenceCountedOpenSslEngine.java:734) ~[netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.wrap(ReferenceCountedOpenSslEngine.java:711) ~[netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at javax.net.ssl.SSLEngine.wrap(SSLEngine.java:509) ~[?:1.8.0_102]
	at io.netty.handler.ssl.SslHandler.wrap(SslHandler.java:764) ~[netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at io.netty.handler.ssl.SslHandler.wrap(SslHandler.java:596) ~[netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at io.netty.handler.ssl.SslHandler.wrapAndFlush(SslHandler.java:568) ~[netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at io.netty.handler.ssl.SslHandler.flush(SslHandler.java:549) ~[netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:777) [netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:769) [netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:750) [netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.flush(CombinedChannelDuplexHandler.java:530) [netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:115) [netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at io.netty.channel.CombinedChannelDuplexHandler.flush(CombinedChannelDuplexHandler.java:355) [netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:777) [netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:769) [netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:750) [netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at io.netty.channel.ChannelDuplexHandler.flush(ChannelDuplexHandler.java:117) [netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:777) [netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:769) [netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
...
```

```
$ md5sum netty-all-4.1.8.Final-SNAPSHOT.jar 
9b729fc5155999e5ea46c3ef889844fc  netty-all-4.1.8.Final-SNAPSHOT.jar
```

**Comment by normanmaurer** [comment]
@rkapsi can you tell me what commit the snapshot is on ?

**Comment by rkapsi** [comment]
That is the current/most recent nightly.

```
netty-all-4.1.8.Final-20170120.120745-9.jar	Fri Jan 20 12:07:46 UTC 2017	3599129
```

**Comment by normanmaurer** [comment]
@rkapsi hmm... I will have a look ( can you open a new issue with the stack please ?)

**Comment by normanmaurer** [comment]
@rkapsi I created it as https://github.com/netty/netty/issues/6260 ... will investigate
