### ISSUE TITLE
Test failure in OpenJDK 8u141-jdk Docker container

### ISSUE THREAD

**Issue by mkw** [netty/netty#7351]
### Expected behavior

The Epoll implementation works in the OpenJDK 8u141-jdk Docker container.

I know that Netty doesn't specifically target Netty, but this is the official OpenJDK build (https://hub.docker.com/_/openjdk/), and is used to work.  I assume that something changed in the OS being used to build the official OpenJDK image.  I noticed this line in the Netty build output:

```
[INFO] --- build-helper-maven-plugin:1.10:regex-property (regex-combined-sendmmsg) @ netty-transport-native-epoll ---
[INFO] No match to regex '.*IO_NETTY_SENDMSSG_NOT_FOUND.*' found in '4.9.49-mobyldd (Debian GLIBC 2.24-11+deb9u1) 2.24'. The initial value '4.9.49-mobyldd (Debian GLIBC 2.24-11+deb9u1) 2.24' is left as-is...
```

### Actual behavior

Run:

`docker run -it -v `pwd`:`pwd` -v ~/.m2:/root/.m2 -w `pwd` netty-build mvn install --fae -pl transport-native-epoll`

In the output, one of the tests fails because getsockopt() throws "Operation not supported" somewhere in the native code:

```
Tests run: 9, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.001 sec <<< FAILURE! - in io.netty.channel.epoll.EpollSocketTest
testTrafficClass(io.netty.channel.epoll.EpollSocketTest)  Time elapsed: 0 sec  <<< ERROR!
io.netty.channel.ChannelException: getsockopt() failed: Operation not supported
```

In my own application code, I saw the following fragment of a stack trace when trying to get a list of supported options on a channel:

```
    io.netty.channel.ChannelException: getsockopt() failed: Operation not supported
        at io.netty.channel.unix.Socket.getTrafficClass(Native Method)
        at io.netty.channel.unix.Socket.getTrafficClass(Socket.java:368)
        at io.netty.channel.epoll.EpollSocketChannelConfig.getTrafficClass(EpollSocketChannelConfig.java:197)
        at io.netty.channel.epoll.EpollSocketChannelConfig.getOption(EpollSocketChannelConfig.java:88)
        at io.netty.channel.DefaultChannelConfig.getOptions(DefaultChannelConfig.java:94)
        at io.netty.channel.epoll.EpollSocketChannelConfig.getOptions(EpollSocketChannelConfig.java:58)
```

### Steps to reproduce

Use this Dockerfile and build it (e.g. `docker build -t natty-build .`).

```
FROM openjdk:8u141-jdk

RUN apt-get update -y && \
    apt-get install -yq \
      autoconf \
      automake \
      libtool \
      make \
      tar \
      libaio-dev \
      libssl-dev \
      libapr1-dev \
      lksctp-tools && \
    apt-get clean

ARG MAVEN_VERSION=3.5.2
ARG MAVEN_SHA=707b1f6e390a65bde4af4cdaf2a24d45fc19a6ded00fff02e91626e3e42ceaff
ARG MAVEN_BASE_URL=http://www-us.apache.org/dist/maven/maven-3/${MAVEN_VERSION}/binaries

RUN mkdir -p /usr/share/maven && \
    curl -fsSL -o /tmp/apache-maven.tar.gz ${MAVEN_BASE_URL}/apache-maven-$MAVEN_VERSION-bin.tar.gz && \
    echo "${MAVEN_SHA}  /tmp/apache-maven.tar.gz" | sha256sum -c - && \
    tar -xzf /tmp/apache-maven.tar.gz -C /usr/share/maven --strip-components=1 && \
    rm -f /tmp/apache-maven.tar.gz && \
    ln -s /usr/share/maven/bin/mvn /usr/bin/mvn

ENV MAVEN_HOME /usr/share/maven

VOLUME /root/.m2
VOLUME /opt/netty

WORKDIR /opt/netty

CMD ["/bin/bash"]
```

Run a build using: `docker run -it -v `pwd`:`pwd` -v ~/.m2:/root/.m2 -w `pwd` netty-build mvn install --fae`

### Minimal yet complete reproducer code (or URL to code)

Existing test fails.

### Netty version

4.1.16.Final

### JVM version (e.g. `java -version`)

8u141-jdk

### OS version (e.g. `uname -a`)

Based on Debian Stretch.

**Comment by normanmaurer** [comment]
This was fixed here:

https://github.com/netty/netty/pull/7278

Will be part of the next release

**Comment by mkw** [comment]
Thanks -- sorry I missed that one before reporting this.

**Comment by normanmaurer** [comment]
No worries 👍

**Comment by mkw** [comment]
Trying to figure out the real cause, but `io.netty.channel.epoll.EpollSocketChannelConfig#getOptions` is still failing in 4.1.17.Final with:

```
    io.netty.channel.ChannelException: getsockopt() failed: Protocol not available
        at io.netty.channel.epoll.LinuxSocket.isTcpFastOpenConnect(Native Method)
        at io.netty.channel.epoll.LinuxSocket.isTcpFastOpenConnect(LinuxSocket.java:63)
        at io.netty.channel.epoll.EpollSocketChannelConfig.isTcpFastOpenConnect(EpollSocketChannelConfig.java:544)
        at io.netty.channel.epoll.EpollSocketChannelConfig.getOption(EpollSocketChannelConfig.java:119)
        at io.netty.channel.DefaultChannelConfig.getOptions(DefaultChannelConfig.java:94)
        at io.netty.channel.epoll.EpollSocketChannelConfig.getOptions(EpollSocketChannelConfig.java:58)
```

I'll make a new issue since this does not seem to be related to the traffic class, but fast open, which also is calling getsockopt() internally.

**Comment by normanmaurer** [comment]
@mkw https://github.com/netty/netty/pull/7407 ... This should fix it.
