### ISSUE TITLE
Illegal reflective access using Netty with openjdk-11 (docker + vertx 3.6.0)

### ISSUE THREAD

**Issue by violette** [netty/netty#9016]
Hi all! I'll open that issue, I hope you guys could fix it ;) Tell me if you need more details.
Enjoy,

### Expected behavior
No warning about illegal reflective access

### Actual behavior

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by io.netty.resolver.dns.DefaultDnsServerAddressStreamProvider (file:/opt/ig/lib/netty-resolver-dns-4.1.30.Final.jar) to method sun.net.dns.ResolverConfiguration.open()
WARNING: Please consider reporting this to the maintainers of io.netty.resolver.dns.DefaultDnsServerAddressStreamProvider
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```
### Steps to reproduce

The application I used is based on vertx-web 3.6.0. When docker images starts up, the warnings are displayed.

### Netty version
4.1.30.Final.jar

### JVM version (e.g. `java -version`)
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment (build 11.0.2+9-Debian-3bpo91)
OpenJDK 64-Bit Server VM (build 11.0.2+9-Debian-3bpo91, mixed mode)

### OS version (e.g. `uname -a`)
Linux a1c4824fa6a8 4.20.11-100.fc28.x86_64 #1 SMP Wed Feb 20 15:51:24 UTC 2019 x86_64 GNU/Linux

**Comment by normanmaurer** [comment]
@violette this is fixed in the latest netty release. Please upgrade.

**Comment by violette** [comment]
@normanmaurer  This comes from the vertx-web 3.6.0 which embeds Netty 4.1.30Final. Thank you!

**Comment by normanmaurer** [comment]
@violette vertx will need to upgrade then.

**Comment by yay** [comment]
Still an issue with Netty 4.1.39.Final used by latest vertx.

**Comment by normanmaurer** [comment]
We recently fixed another one as part of 4.1.41.Final
