### ISSUE TITLE
Increased memory footprint in 4.1.43.Final

### ISSUE THREAD

**Issue by millems** [netty/netty#9768]
### Expected behavior

Memory usage should not largely increase between Netty versions.

### Actual behavior

Memory usage increased in user application tests, and `io.netty.testsuite.transport.socket.SocketSslEchoTest#testSslEcho()` netty test.

**4.1.42.Final**

Heap Usage: 59 MB
Non-Heap Usage: 41 MB

![Screen Shot](https://user-images.githubusercontent.com/24903526/68501642-73e14a00-0213-11ea-95f1-27a0173e5d1a.png)

**4.1.43.Final**

Heap Usage: 241 MB
Non-Heap Usage: 41 MB

![Screen Shot](https://user-images.githubusercontent.com/24903526/68501669-85c2ed00-0213-11ea-91cb-d142c3a9cc58.png)

Note: While this is listed as "byte[]", it's just more PoolChunks (except for the Stack Local listed above):

![Screen Shot](https://user-images.githubusercontent.com/24903526/68501886-14d00500-0214-11ea-99ad-d725d96166a2.png)

**Initial Analysis**

I'm still working to identify the source of this difference between the two versions. I'll update this issue as I find more information.

### Steps to reproduce

1. `git checkout netty-4.1.42.Final`
2. Benchmark memory usage DURING execution of  io.netty.testsuite.transport.socket.SocketSslEchoTest#testSslEcho()
3. `git checkout netty-4.1.43.Final`
4. Benchmark memory usage DURING execution of  io.netty.testsuite.transport.socket.SocketSslEchoTest#testSslEcho()
5. Compare memory usage

### Minimal yet complete reproducer code (or URL to code)

[SocketSslEchoTest#testSslEcho()](https://github.com/netty/netty/blob/4.1/testsuite/src/main/java/io/netty/testsuite/transport/socket/SocketSslEchoTest.java#L239-L242)

### Netty version

4.1.43.Final

### JVM version (e.g. `java -version`)

openjdk version "1.8.0_232"
OpenJDK Runtime Environment Corretto-8.232.09.1 (build 1.8.0_232-b09)
OpenJDK 64-Bit Server VM Corretto-8.232.09.1 (build 25.232-b09, mixed mode)

### OS version (e.g. `uname -a`)

Darwin 38f9d3cc3b07.ant.amazon.com 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64

**Comment by njhill** [comment]
@millems it looks like you meant 4.1.43.Final in the title (rather than 1.4.34.Final)?

**Comment by millems** [comment]
> @millems it looks like you meant 4.1.43.Final in the title (rather than 1.4.34.Final)?

Good call, will fix.

**Comment by millems** [comment]
Testing of application-level code shows a different picture of things...

**4.1.42**

<img width="1053" alt="Screen Shot 2019-11-08 at 3 11 43 PM" src="https://user-images.githubusercontent.com/24903526/68516899-3c39c880-023a-11ea-8da4-e62ee31524ba.png">

**4.1.43**

<img width="1056" alt="Screen Shot 2019-11-08 at 3 11 55 PM" src="https://user-images.githubusercontent.com/24903526/68516913-4bb91180-023a-11ea-92a4-bb916f5b45da.png">

The test code: https://github.com/aws/aws-sdk-java-v2/blob/master/test/stability-tests/src/it/java/software/amazon/awssdk/stability/tests/s3/S3AsyncStabilityTest.java#L51-L56

**Comment by millems** [comment]
GC root of these retained pool chunks are the same...

<img width="992" alt="Screen Shot 2019-11-08 at 3 14 46 PM" src="https://user-images.githubusercontent.com/24903526/68517003-8de25300-023a-11ea-82d9-e806b1205b3c.png">

**Comment by njhill** [comment]
Without looking too closely it seems quite likely to be related to #9696. @millems presumably you are using JDK SSL provider for your test - would you be able to try it with the OpenSSL provider if so (using `netty-tcnative`)?

**Comment by millems** [comment]
@njhill Will give it a shot with netty-tcnative.

**Comment by millems** [comment]
@njhill Yep, switching to openssl fixed it for me. Good call. I believe this is a total memory increase, not just an increase in heap memory with an equal, corresponding decrease in direct memory.

I'll double check that, unless the ~16 MB * event loop size memory footprint increase is by design?

**Comment by njhill** [comment]
My assumption is that heap buffers were not previously used and so the heap pools never grew. I think the idea of the change is that transient heap allocations would be done anyhow by the JDK SSL impl otherwise.

But yes I guess at least with the default configuration, going from not using pooled heap buffers to using them means a minimum of ~16MB * EL thread count increase in "static" allocations.

Probably we want the behaviour to be something like: use a pooled heap buf if heap pools are already in use, otherwise use unpooled heap... not sure how easy that would be to achieve with the existing abstractions.

If you wanted to experiment further, you could try providing a custom `ByteBufAllocator` which just delegates to the pooled allocator for direct buffers and unpooled for heap.

Something else to consider is that despite increased mem footprint overall footprint being higher, overall performance may be better because of reduced ongoing allocations and GC pressure. I'd be interested whether you observed any improvement of this kind when moving from 4.1.42.Final to 4.1.43.Final?

**Comment by millems** [comment]
Just verified that your assumption seems correct. There's no difference in direct memory usage, and this is the first use of heap buffers in our particular case.

Let me see what the throughput differences looks like on our end...

**Comment by millems** [comment]
The throughput seems a little better for our netty in 4.1.43, but not 16 MB * EL thread count better:

**4.1.42.Final**

NettyClientH1NonTlsBenchmark.concurrentApiCall                 N/A  thrpt   10  11250.608 ± 289.318  ops/s 
NettyClientH1NonTlsBenchmark.sequentialApiCall                 N/A  thrpt   10   3406.554 ± 257.252  ops/s 
NettyHttpClientH1Benchmark.concurrentApiCall                   jdk  thrpt   10   9255.370 ± 318.070  ops/s 
NettyHttpClientH1Benchmark.sequentialApiCall                   jdk  thrpt   10   2383.520 ±  17.872  ops/s 
NettyHttpClientH2Benchmark.concurrentApiCall                   jdk  thrpt   10   6945.515 ±  44.315  ops/s 
NettyHttpClientH2Benchmark.sequentialApiCall                   jdk  thrpt   10   2340.305 ±  24.635  ops/s 

**4.1.43.Final**

NettyClientH1NonTlsBenchmark.concurrentApiCall                 N/A  thrpt   10  11444.541 ± 307.407  ops/s 
NettyClientH1NonTlsBenchmark.sequentialApiCall                 N/A  thrpt   10   3421.872 ±  37.874  ops/s 
NettyHttpClientH1Benchmark.concurrentApiCall                   jdk  thrpt   10   9558.505 ± 319.858  ops/s 
NettyHttpClientH1Benchmark.sequentialApiCall                   jdk  thrpt   10   2465.659 ±  32.987  ops/s 
NettyHttpClientH2Benchmark.concurrentApiCall                   jdk  thrpt   10   7043.171 ±  59.038  ops/s 
NettyHttpClientH2Benchmark.sequentialApiCall                   jdk  thrpt   10   2445.492 ±  33.559  ops/s

**Comment by njhill** [comment]
@normanmaurer WDYT about only using pooled heap buffer here if they are already in use?

**Comment by normanmaurer** [comment]
@njhill how would you know ?

**Comment by njhill** [comment]
@normanmaurer I hadn't considered the "how" much yet, but can give it some more thought :) was just contemplating what the ideal balance might be given the new behaviour seems undesirable in this (presumably not uncommon) case...

**Comment by normanmaurer** [comment]
@njhill I see... its a good question and sadly the answer is "I dont know"... :(

**Comment by njhill** [comment]
@millems I have not thought of a good "automatic" solution yet but realized you can do what I suggested [above](https://github.com/netty/netty/issues/9768#issuecomment-552036485) without any code change, just set system property `-Dio.netty.allocator.numHeapArenas=0`. This should fix the memory issue and perf should hopefully still be similar to or slightly better than before.

The downside I guess is that the user may be using netty for something else in the same JVM where they do want to use pooled heap buffers...

**Comment by millems** [comment]
@njhill Unfortunately as a fellow client library, we can't set system properties on behalf of our customers. We have to keep our use of netty self-contained so that they can do whatever they want outside of the use of the SDK.

Is it possible for us to provide a different byte buffer allocator that uses unpooled memory instead? I don't see a way, since it looks like multiple parts of the code base go back to the default allocator, which can only be controlled by system properties.

**Comment by johnou** [comment]
@millems did you confirm https://github.com/netty/netty/pull/9696 is to blame for the increase in heap?

**Comment by millems** [comment]
@johnou I haven't directly verified by reverting just that one commit locally. I could try that out when my bandwidth opens up again in a few weeks, if we're unsure whether that's the cause.

**Comment by njhill** [comment]
> Is it possible for us to provide a different byte buffer allocator that uses unpooled memory instead?

@millems yes that was my original suggestion - you can provide a custom allocator to the channel bootstrap, e.g.
```java
.option(ChannelOption.ALLOCATOR, myAllocator)
```

**Comment by johnou** [comment]
@millems be warned that will most likely come with a negative performance hit..

**Comment by partheinstein** [comment]
I tried setting `-Dio.netty.allocator.numHeapArenas=0` but it doesn't seem to work, probably because of [this](https://github.com/netty/netty/blob/07149729cc4c629200a0ca8f8e63f54ee05601c8/buffer/src/main/java/io/netty/buffer/PooledByteBufAllocator.java#L100) (number of chunks cannot be zero).

```
Name Count Size Retained
byte[]	66,731 (21.8%)	74,161,509 B (83.7%)	72,800,074 B (82.2%)
```

```
Name Count Size Retained
io.netty.buffer.PoolChunk	8 (0%)	1,008 B (0%)	67,308,176 B (76%)
 io.netty.buffer.PoolChunk#2		126 B (0%)	16,802,142 B (19%)
 io.netty.buffer.PoolChunk#4		126 B (0%)	16,802,142 B (19%)
 io.netty.buffer.PoolChunk#6		126 B (0%)	16,802,142 B (19%)
 io.netty.buffer.PoolChunk#8		126 B (0%)	16,802,142 B (19%)
 io.netty.buffer.PoolChunk#1		126 B (0%)	24,902 B (0%)
 io.netty.buffer.PoolChunk#3		126 B (0%)	24,902 B (0%)
 io.netty.buffer.PoolChunk#5		126 B (0%)	24,902 B (0%)
 io.netty.buffer.PoolChunk#7		126 B (0%)	24,902 B (0%)
```

The retained size remained the same despite the JVM property.

However setting channel's bytebuf as `UnpooledByteBufAllocator.DEFAULT` does result in no pool chunks in the heap.

```
Name Count Size Retained
byte[]	66,526 (22.4%)	6,999,297 B (35.7%)	5,644,283 B (28.8%)
```

**Comment by raghavb1979** [comment]
Hello I am also facing a similar issue when took a heap dump and checked in the eclipse MAT it is showing the leak as io.netty.buffer.PoolChunk ( 54.28%) occupied. Is there any way to trace this problem? Does this problem will get solved by defining -Dio.netty.allocator.numHeapArenas=0?
Please let me know.

**Comment by msilva123** [comment]
Hi, is there a workaround for this issue?

**Comment by normanmaurer** [comment]
Let me have a look... Sorry I totally lost track of this one

**Comment by juliojgd** [comment]
@normanmaurer It confuses me. Has been comitted any solution to this in 4.1.59.Final release? Because it displays in the release 4.1.59.Final changelog but surprisingly it is Open.

Can I interpret that this is a known and ongoing (not resolved) issue?

**Comment by tmulle** [comment]
Hi, just wondering if this has been fixed in 4.1.59.Final? We are currently running into this memory issue when using the default SSLEngine (JDK). If we switch to OpenSSL it fixes the pooled memory issue but then we are faced with cipher suite availability differences between JDK and OpenSSL. We'd like to stick to the JDK version if possible since our legacy product is using that engine with our hardware products.

Thanks..

**Comment by PascalSchumacher** [comment]
>just wondering if this has been fixed in 4.1.59.Final?

I think not, was this issue is still open and we are still seeing this behavior in `4.1.59.Final`.

**Comment by gopiharis** [comment]
Hi, we are facing same issue. any known workaround or stable older version i can use to mitigate this issue?

**Comment by tmulle** [comment]
I heard that switching to OpenSSL fixes the issue. We are using SSL in our pipelines and switching to OpenSSL did fix the memory issue.
However, we ran into an issue with OpenSSL not supporting an older cipher so we had to revert back to the JDK SSL engine.

Because of this, I ended up using this line of code to turn off the memory caching until a solution is found. I heard about it on the forums.

// Turn off buffering of memory
bs.option(ChannelOption.ALLOCATOR, UnpooledByteBufAllocator.DEFAULT);

We haven’t found any issues so far, other than possible the garbage collector works a little harder. But that could be our program itself and 
Not necessarily Netty.

**Comment by chrisvest** [comment]
Besides `-Dio.netty.allocator.numHeapArenas=`, another option that may be of interest is `-Dio.netty.allocator.maxOrder=` which is set to `11` by default, which in turn means the memory will be allocated in 16 MiB chunks. Setting this to a lower value will make the chunks smaller; by half per point, e.g. 10 gives 8 MiB chunks, 9 gives 4 MiB, etc.

**Comment by Rishabh-Handa** [comment]
> @millems I have not thought of a good "automatic" solution yet but realized you can do what I suggested [above](https://github.com/netty/netty/issues/9768#issuecomment-552036485) without any code change, just set system property `-Dio.netty.allocator.numHeapArenas=0`. This should fix the memory issue and perf should hopefully still be similar to or slightly better than before.
> 
> The downside I guess is that the user may be using netty for something else in the same JVM where they do want to use pooled heap buffers...

Hi @njhill, what are the drawbacks of setting `Dio.netty.allocator.numHeapArenas=0` ?

We are using `JMS`, which internally, to create connection makes use of `org.apache.qpid.jms.provider.amqp.AmqpProvider`
which by deafult instantiates `PooledByteBufAllocator`, hence, PoolChunks are retained in the heap memory

Could there be any issues while sending/receiving messages if we set `Dio.netty.allocator.numHeapArenas=0` ?

**Comment by chrisvest** [comment]
@handaj If you set `-Dio.netty.allocator.numHeapArenas=0` then heap buffers won't be cached and reused. You'll have more allocation going on, and thus more GC work. On the other hand, max heap size might in theory be smaller since there's no cache that'll hold on to memory that isn't used.

**Comment by franz1981** [comment]
If you feel that qpid JMS should just use off heap buffers for that use
case I suggest to open an issue on qpid JMS too :)


Il ven 9 lug 2021, 04:36 rishabh ***@***.***> ha scritto:

**Comment by gemmellr** [comment]
Did you miss the bit where it is apparently Netty itself that is deliberately creating the on-heap buffers @franz1981? :)

**Comment by franz1981** [comment]
@gemmellr yep, don't have my laptop with me ATM, but yep, if the heap buffer has been allocated in some Netty handler qpid jms cannot do anything to help

**Comment by dogmimichen** [comment]
Hi all, I'm looking into some code and found that some of our code use UnpooledByteBufAllocator instead of PooledByteBufAllocator because of this issue. It looks like this particular issue is not fixed yet however there's a commit: (Reduce the default PooledByteBufAllocator chunk size from 16 MiB to 4 MiB) https://github.com/netty/netty/pull/12108/commits/c4ba497f52 which mentions that it fixed the issue. I'm a little confused what's the status of this issue. Also want to know more about how much % memory increased are we expecting here? would it be infinite or constrained. Our application is latency sensitive and I can see switching to PooledByteBufAllocator definitely help so want to know more details

**Comment by dogmimichen** [comment]
Hi @normanmaurer, any chance to release in next milestone ?

**Comment by franz1981** [comment]
@dogmimichen just curious: separated but related question. How many event loops threads are you currently creating with your application based on Netty?

**Comment by dogmimichen** [comment]
it's normal setup, parent group is single thread, child group is configuring thread counts as processor counts. Anything you think is related to this issue ? @franz1981

**Comment by chrisvest** [comment]
I took a look at `SocketSslEchoTest` again, to compare the `PooledByteBufAllocator` to the `AdaptiveByteBufAllocator`.

With the `PooledByteBufAllocator`, I can take a heap dump and query the memory used by all the `PoolChunk` objects.
The `select "" + sum(heap.objects('io.netty.buffer.PoolChunk'), 'it.chunkSize')` query gives me `37748736`, so ~37.7 MiB.

With the `AdaptiveByteBufAllocator`, I can take a heap dump and query the memory used by all the `Chunk` objects.
The `select ""+sum(heap.objects('io.netty.buffer.AdaptivePoolingAllocator$Chunk'), 'it.capacity')` query gives me `7536640`, so ~7.5 MiB.

I think we can close this, because `PooledByteBufAllocator` in this test used less memory than the 4.1.42 baseline used by the reporter, since pool chunks are now 4 MiB instead of 16 MiB, and have been for a while. Also, options exist to get even lower memory usage with the experimental `AdaptiveByteBufAllocator` introduced in 4.1.110.
